# Generated by Django 5.0.6 on 2024-07-10 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_category_options_alter_category_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("category", "name")},
        ),
    ]
